"""create_date changed in models charityproject and donation

Revision ID: 92a90db341eb
Revises: 19d726123156
Create Date: 2024-11-04 19:51:36.235557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a90db341eb'
down_revision = '19d726123156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
